# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SADMVN <- function(M, C) {
    .Call(`_lxsplines_SADMVN`, M, C)
}

TriNProb <- function(mean, cv) {
    .Call(`_lxsplines_TriNProb`, mean, cv)
}

BivNProb <- function(mean, cv) {
    .Call(`_lxsplines_BivNProb`, mean, cv)
}

rtmvn <- function(tMean, tVar) {
    .Call(`_lxsplines_rtmvn`, tMean, tVar)
}

qcopy <- function(a, b, c, d) {
    .Call(`_lxsplines_qcopy`, a, b, c, d)
}

polyaGamma <- function(X, truncate) {
    .Call(`_lxsplines_polyaGamma`, X, truncate)
}

sampleBetas <- function(ttY, ttX, tbetas, LAM, intLAM, p, tau, omega) {
    .Call(`_lxsplines_sampleBetas`, ttY, ttX, tbetas, LAM, intLAM, p, tau, omega)
}

sinsertBeta_trivariate <- function(tY, Xidx, ctau, tp, lam, omega) {
    .Call(`_lxsplines_sinsertBeta_trivariate`, tY, Xidx, ctau, tp, lam, omega)
}

sdeleteBeta_trivariate <- function(tY, Xidx, ctau, tp, lam, omega) {
    .Call(`_lxsplines_sdeleteBeta_trivariate`, tY, Xidx, ctau, tp, lam, omega)
}

sinsertBeta_bivariate <- function(tY, Xidx, ctau, tp, lam, omega) {
    .Call(`_lxsplines_sinsertBeta_bivariate`, tY, Xidx, ctau, tp, lam, omega)
}

sdeleteBeta_bivariate <- function(tY, Xidx, ctau, tp, lam, omega) {
    .Call(`_lxsplines_sdeleteBeta_bivariate`, tY, Xidx, ctau, tp, lam, omega)
}

shapesplineInsertQuadratic <- function(k, tp, txi, tdeg, tCBX, tpos) {
    .Call(`_lxsplines_shapesplineInsertQuadratic`, k, tp, txi, tdeg, tCBX, tpos)
}

shapesplineDeleteQuadratic <- function(k, tp, txi, tdeg, tCBX, tpos) {
    .Call(`_lxsplines_shapesplineDeleteQuadratic`, k, tp, txi, tdeg, tCBX, tpos)
}

shapesplineInsertLinear <- function(k, tp, tdeg, tCBX, tpos) {
    .Call(`_lxsplines_shapesplineInsertLinear`, k, tp, tdeg, tCBX, tpos)
}

shapesplineDeleteLinear <- function(k, tp, tdeg, tCBX, tpos) {
    .Call(`_lxsplines_shapesplineDeleteLinear`, k, tp, tdeg, tCBX, tpos)
}

